#!/usr/bin/env bash

handle() {
  case $1 in
    monitoradded*) hyprctl keyword monitor "eDP-1, disable" ;;
    monitorremoved*) hyprctl keyword monitor "eDP-1, highres, auto, auto" ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
